# Starship prompt config
# Docs: https://starship.rs/config/

# Timeout for commands that starship runs (ms)
command_timeout = 1000

# Newline between prompts
add_newline = false

# Prompt format (two lines: info on top, character below)
format = "$directory$git_branch$git_status$nodejs$bun$cmd_duration\n$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
home_symbol = "ï€• ~"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
format = "[$symbol($version)]($style) "

[package]
disabled = true

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "

[bun]
format = "[$symbol($version)]($style) "
